# Generated by Django 4.0.4 on 2022-05-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_app', '0002_alter_issue_assignee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'back-end')], max_length=255),
        ),
    ]
