# Generated by Django 4.0.4 on 2022-05-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_app', '0003_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('BE', 'back-end'), ('FE', 'front-end'), ('IOS', 'ios'), ('AD', 'android')], max_length=255),
        ),
    ]
