# Generated by Django 4.0.4 on 2022-05-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_app', '0004_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MED', 'medium'), ('HIGH', 'high')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to_DO'), ('IN_PROGRESS', 'in_progress'), ('DONE', 'done')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'bug'), ('UPGRADE', 'upgrade'), ('TASK', 'task')], max_length=255),
        ),
    ]
