# Generated by Django 4.0.4 on 2022-05-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_app', '0005_alter_issue_priority_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to_do'), ('IN_PROGRESS', 'in_progress'), ('DONE', 'done')], max_length=255),
        ),
    ]
